--1: What is the total number of users registered on the platform?

SELECT COUNT(*) AS total_users
FROM all_users;

-- Q2: What is the total number of transactions performed on the platform?

SELECT COUNT(*) AS total_transactions
FROM all_transactions;

-- Q3: What is the total transaction value generated by the platform?

SELECT SUM("Amount") AS total_transaction_value
FROM all_transactions;

-- Q4: What is the distribution of successful vs failed transactions?

SELECT
    "Payment_Status",
    COUNT(*) AS total_transactions
FROM all_transactions
GROUP BY "Payment_Status"
ORDER BY total_transactions DESC;

-- Q5: Which service category generates the highest revenue?

SELECT
    "Service",
    SUM("Amount") AS total_revenue
FROM all_transactions
GROUP BY "Service"
ORDER BY total_revenue DESC;

-- Q6: What is the total spending made by each user across all transactions?

SELECT
    u.user_id,
    u.name,
    SUM(t."Amount") AS total_spending
FROM all_users u
JOIN all_transactions t
ON u.user_id = t."User_ID"
GROUP BY u.user_id, u.name
ORDER BY total_spending DESC;

-- Q7: Which users have never performed any transaction on the platform?

SELECT
    u.User_ID,
    u.Name
FROM all_users u
LEFT JOIN all_transactions t
ON u.User_ID = t."User_ID"
WHERE t."Transaction_ID" IS NULL;

-- Q8: Which users have spent more than the average transaction amount?

SELECT
    "User_ID",
    SUM("Amount") AS total_spent
FROM all_transactions
GROUP BY "User_ID"
HAVING SUM("Amount") >
(
    SELECT AVG("Amount")
    FROM all_transactions
);

-- Q9: What is the monthly transaction revenue trend over time?

WITH monthly_revenue AS
(
    SELECT
        EXTRACT(YEAR FROM TO_DATE("Transaction_Date",'MM/DD/YYYY')) AS year_no,
        EXTRACT(MONTH FROM TO_DATE("Transaction_Date",'MM/DD/YYYY')) AS month_no,
        SUM("Amount") AS revenue
    FROM all_transactions
    GROUP BY
        EXTRACT(YEAR FROM TO_DATE("Transaction_Date",'MM/DD/YYYY')),
        EXTRACT(MONTH FROM TO_DATE("Transaction_Date",'MM/DD/YYYY'))
)

SELECT *
FROM monthly_revenue
ORDER BY year_no, month_no;
-- Q10: Who are the Top 10 customers based on total transaction value?

WITH customer_spending AS
(
    SELECT
        "User_ID",
        SUM("Amount") AS total_spent
    FROM all_transactions
    GROUP BY "User_ID"
)

-- Convert date column
ALTER TABLE all_transactions
ALTER COLUMN "Transaction_Date"
TYPE DATE
USING TO_DATE("Transaction_Date",'MM/DD/YYYY');

-- Rename columns
ALTER TABLE all_transactions RENAME COLUMN "Amount" TO amount;
ALTER TABLE all_transactions RENAME COLUMN "User_ID" TO user_id;
ALTER TABLE all_transactions RENAME COLUMN "Transaction_Date" TO transaction_date;

-- Q11: Rank all users based on their total spending on the platform.

SELECT
    user_id,
    SUM(amount) AS total_spent,
    RANK() OVER(
        ORDER BY SUM(amount) DESC
    ) AS user_rank
FROM all_transactions
GROUP BY user_id;

-- Q12: Calculate the running cumulative revenue generated by the platform over time.

SELECT
    transaction_date,
    amount,
    SUM(amount) OVER(
        ORDER BY transaction_date
    ) AS running_revenue
FROM all_transactions;

-- Q13: Calculate Month-over-Month (MoM) revenue growth percentage.

WITH monthly_revenue AS
(
    SELECT
        DATE_TRUNC('month', transaction_date) AS month,
        SUM(amount) AS revenue
    FROM all_transactions
    GROUP BY DATE_TRUNC('month', transaction_date)
)

SELECT
    month,
    revenue,
    LAG(revenue) OVER(ORDER BY month) AS previous_revenue,
    ROUND(
        (
            revenue - LAG(revenue) OVER(ORDER BY month)
        ) * 100.0 /
        LAG(revenue) OVER(ORDER BY month),
        2
    ) AS growth_percentage
FROM monthly_revenue;

-- Q14: Segment customers into Low, Medium, High and VIP categories based on spending behavior.

SELECT
    user_id,
    SUM(amount) AS total_spent,

    CASE
        WHEN SUM(amount) < 5000 THEN 'Low Value'
        WHEN SUM(amount) < 15000 THEN 'Medium Value'
        WHEN SUM(amount) < 30000 THEN 'High Value'
        ELSE 'VIP Customer'
    END AS customer_segment

FROM all_transactions
GROUP BY user_id
ORDER BY total_spent DESC;

-- Q15: Create a reusable User Transaction Summary View.

CREATE VIEW user_transaction_summary AS

SELECT
    user_id,
    COUNT("Transaction_ID") AS total_transactions,
    SUM(amount) AS total_spent,
    AVG(amount) AS average_transaction_value
FROM all_transactions
GROUP BY user_id;

SELECT *
FROM user_transaction_summary
ORDER BY total_spent DESC;